### ISSUE TITLE
请问编译报这样的错是什么原因

### ISSUE THREAD

**Issue by geeyu** [calvinwilliams/logpipe#1]
![image](https://user-images.githubusercontent.com/20036057/42088488-31228ab8-7bcc-11e8-836c-279c08a1690c.png)

make: Warning: File `makeinstall' has modification time 1.1e+03 s in the future
gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing -I. -I/root/include -std=gnu99  -c list.c
gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing -I. -I/root/include -std=gnu99  -c rbtree.c
gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing -I. -I/root/include -std=gnu99  -c fasterjson.c
gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing -I. -I/root/include -std=gnu99  -c LOGC.c
LOGC.c: In function ‘WriteLogBaseV’:
LOGC.c:133:8: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   WRITE( 1 , log_buffer , log_buflen );
        ^

**Comment by calvinwilliams** [comment]
你的编译器太严格了。
在makefile.Linux里的CC追加-Werror=unused-result试试。
